### ISSUE TITLE
[BUG] Update USWDS name

### ISSUE THREAD

**Issue by afeijoo** [formio/uswds#105]
Can you please update the description for this repo  to use `System` instead of `Standard` in the name of USWDS? 

It currently says, "JavaScript Powered Forms for the United States Web Design Standard." 

I would expect it to say, "JavaScript Powered Forms for the United States Web Design System."

<img width="929" alt="Screen Shot 2020-07-22 at 5 22 09 PM" src="https://user-images.githubusercontent.com/400690/88230242-0b6eb780-cc40-11ea-9eef-6e6f12dd0022.png">

**Comment by travist** [comment]
Done.  Thanks for the feedback.
