### ISSUE TITLE
Trying to use the system, but parts missing

### ISSUE THREAD

**Issue by arogl** [formio/uswds#217]
Looking to reuse this for our own Government Tell Us Once platform in Queensland, Australia

1. I'm trying to piece together how the address component works.

I can see the actual form field here:
https://github.com/formio/uswds/blob/c14f0fa058bc228df379cb15dba4f5bc6f291b2c/src/templates/uswds/address/form.ejs#L21

But I can't find the definition for the form builder UI - where is the checkbox below defined:  Can't find address? Switch to manual mode.   Not in that repo it seems.
![Pic1](https://user-images.githubusercontent.com/1115472/146289643-9c912ee1-0bf0-45cb-94da-0c4e0e0a85a6.png)

 

2. Can we extend the base to add another provider option? would be good if could have a provider tab on normal input fields so if the agency uses TUO and want's pre-fill it's optional to enable.
 
![Pic2](https://user-images.githubusercontent.com/1115472/146289652-20a9fe82-18cb-4166-a01e-f72157374641.png)

**Comment by travist** [comment]
The Edit form's are actually defined as Form.io forms defined in the core renderer @ https://github.com/formio/formio.js/blob/master/src/components/address/editForm/Address.edit.provider.js

These forms can be modified like the following documentation illustrates.

https://help.form.io/developers/form-builder#overriding-behavior

**Comment by murraybauer** [comment]
Thanks @travist

Is the 'Override Behavior' used to define the Edit Form only possible when using the Form Builder SDK embedded on a standalone HTML page?  i.e  can this be achieved in normal the hosted product itself? - such that all the normal project structures, publishing workflows, RBAC security and SSO login etc still apply.
