### ISSUE TITLE
VPAT.JS?

### ISSUE THREAD

**Issue by ashutosh-kendurkar** [formio/uswds#235]
as given in the accessibility guidance, I was looking for VPAT.js but couldn't find the file anywhere.

can you please help with it?

**Comment by brendanbond** [comment]
Hi @ashutosh-kendurkar - you're referring to [this documentation?](https://help.form.io/intro/developer-tool-ecosystem/accessibility) If so, the VPAT module refers to a module that is available to customers of our enterprise platform, please contact sales@form.io for more information. If not, please let me know which accessibility guidance you're referring to, thanks!

**Comment by ashutosh-kendurkar** [comment]
@brendanbond  thank you for the quick reply, I am looking for WCAG 2.1 Level AA compliance, do I have to subscribe to enterprise platform for that?

So community edition does not support any accessibility guideline?

**Comment by brendanbond** [comment]
> I am looking for WCAG 2.1 Level AA compliance, do I have to subscribe to enterprise platform for that?

Yeah AA compliance will come with the VPAT module, which is an offering in our enterprise platform.

> So community edition does not support any accessibility guideline?

I wouldn't say that, although if you're looking for strict WCAG 2.1 AA compliance we offer that via the enterprise VPAT module. The beauty of the community edition is that it's open source, so you yourself can ensure compliance with whatever accessibility guidelines you'd like. Closing this issue for now, please feel free to let me know if you have any additional questions.
